### ISSUE TITLE
Merge to jsc-android-buildscripts upstream

### ISSUE THREAD

**Issue by Kudo** [Kudo/jsc-android-buildscripts#3]
The reason to maintain forked jsc-android-buildscripts is that upstream review and package publish process is getting slow and its CI is broken.
I will merge to upstream if the problems is solved.

**Comment by Kudo** [comment]
@danilobuerger I am sorry to ping you here.
Regarding your mentioned for JSC Intl problem, if you don't mind, please try my forked version at https://www.npmjs.com/package/@kudo-ci/jsc-android/v/250230.2.1.
You could also check the README of how to migrate to the version.
Thank you.

**Comment by danilobuerger** [comment]
@Kudo sure, no problem. I will try to get it done this week and report back.

**Comment by tobi512** [comment]
Hey @danilobuerger, did you have time to try out the fixed version yet?
